/**
 * How big the bowl is, from how many people the venue holds.
 *
 * The number is real and per venue (fixtures/venues.json, generated by
 * scripts/capture-venues.ts from Wikidata and matched only where the match is
 * unarguable). What is derived from it is the size of the bowl and how full it
 * is, never the shape of any particular stadium, which nobody here knows.
 */
import { describe, expect, it } from 'vitest';
import { bowlFor } from '../shared/bowl';
import { VENUES } from '../shared/venues';

describe('the bowl a capacity buys', () => {
  it('is exactly the one Gridiron has always drawn when no capacity is reported', () => {
    const b = bowlFor(null);
    expect(b.capacity).toBeNull();
    expect(b.tiers).toHaveLength(4);
    expect(b.tiers.map((t) => t.rows)).toEqual([9, 9, 6, 6]);
    expect(b.tiers[0].length).toBeCloseTo(150);
    expect(b.tiers[0].depth).toBeCloseTo(26);
    // Undefined and nonsense are the same as unreported, never a bowl of size zero.
    for (const bad of [undefined, 0, -5, Number.NaN]) expect(bowlFor(bad).tiers.map((t) => t.rows)).toEqual([9, 9, 6, 6]);
  });

  it('grows with the crowd, in both directions rather than only upward', () => {
    const big = bowlFor(107_601); // Michigan Stadium
    const mid = bowlFor(70_000);
    const small = bowlFor(25_000);
    expect(big.tiers[0].rows).toBeGreaterThan(mid.tiers[0].rows);
    expect(mid.tiers[0].rows).toBeGreaterThan(small.tiers[0].rows);
    expect(big.tiers[0].length).toBeGreaterThan(small.tiers[0].length);
    /*
     * And the crowd with it. Seat lights are scattered per row along each
     * stand's length, so rows times length is what the bowl actually holds;
     * there is no separate count to keep in step with it.
     */
    const holds = (b: ReturnType<typeof bowlFor>) => b.tiers.reduce((n, t) => n + t.rows * t.length, 0);
    expect(holds(big)).toBeGreaterThan(holds(mid));
    expect(holds(mid)).toBeGreaterThan(holds(small));
  });

  it('takes the ends off a ground too small to have them, which is what those grounds look like', () => {
    expect(bowlFor(800).tiers).toHaveLength(2);
    expect(bowlFor(12_000).tiers).toHaveLength(2);
    expect(bowlFor(20_000).tiers).toHaveLength(4);
    expect(bowlFor(107_601).tiers).toHaveLength(4);
  });

  it('is bounded at both ends, because neither a bowl that vanishes nor one that swallows the field is useful', () => {
    const tiny = bowlFor(1);
    const vast = bowlFor(5_000_000);
    expect(tiny.tiers[0].rows).toBeGreaterThanOrEqual(3);
    expect(vast.tiers[0].rows).toBeLessThanOrEqual(13);
    expect(vast.tiers[0].length).toBeLessThanOrEqual(150 * 1.2);
  });

  it('stands its floodlights clear of the stands they light', () => {
    expect(bowlFor(107_601).towerX).toBeGreaterThan(bowlFor(null).towerX * 0.99);
    expect(bowlFor(800).towerX).toBeCloseTo(84);
  });
});

describe('the checked-in capacity table', () => {
  const table = { venues: VENUES };

  it('cites an entry for every capacity, and claims none without one', () => {
    expect(table.venues.length).toBeGreaterThan(100);
    for (const v of table.venues) {
      expect(v.espnId, v.name).toMatch(/^\d+$/);
      // The two travel together: a capacity always says where it came from, and a row without
      // one never carries an orphaned reference to an entry it did not use.
      if (v.capacity === null) expect(v.wikidata, v.name).toBeNull();
      else {
        expect(v.wikidata, v.name).toMatch(/^Q\d+$/);
        expect(v.capacity, v.name).toBeGreaterThan(0);
      }
    }
  });

  it('carries a surface for every venue, which is the thing the scoreboard never says', () => {
    const withSurface = table.venues.filter((v) => v.grass !== null);
    expect(withSurface.length).toBe(table.venues.length);
  });

  it('holds one row per venue, so a lookup by id can never be ambiguous', () => {
    const ids = table.venues.map((v) => v.espnId);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('has names that repeat, which is exactly why the name fallback drops them', () => {
    // Two different grounds are both called "Greene Stadium". A fallback that picked one would
    // put another venue's facts on a game, so a name that is not unique is not matchable at all.
    const counts = new Map<string, number>();
    for (const v of table.venues) counts.set(v.name, (counts.get(v.name) ?? 0) + 1);
    const repeated = [...counts.entries()].filter(([, n]) => n > 1);
    expect(repeated.length).toBeGreaterThan(0);
    const unique = [...counts.entries()].filter(([, n]) => n === 1);
    expect(unique.length).toBeGreaterThan(table.venues.length * 0.9);
  });

  it('has the ones anybody would check by hand', () => {
    const by = new Map(table.venues.map((v) => [v.name, v]));
    expect(by.get('Michigan Stadium')?.capacity).toBe(107_601);
    expect(by.get('Lambeau Field')?.capacity).toBe(80_750);
    expect(by.get('Ohio Stadium')?.capacity).toBe(102_780);
  });
});
