/**
 * How big the bowl is, from how many people the venue holds.
 *
 * The number is real and per venue (fixtures/venues.json, generated by
 * scripts/capture-venues.ts from Wikidata and matched only where the match is
 * unarguable). What is derived from it is the size of the bowl and how full it
 * is, never the shape of any particular stadium, which nobody here knows.
 */
import { describe, expect, it } from 'vitest';
import { bowlFor } from '../shared/bowl';
import { VENUE_CAPACITIES } from '../shared/venues';

describe('the bowl a capacity buys', () => {
  it('is exactly the one Gridiron has always drawn when no capacity is reported', () => {
    const b = bowlFor(null);
    expect(b.capacity).toBeNull();
    expect(b.tiers).toHaveLength(4);
    expect(b.tiers.map((t) => t.rows)).toEqual([9, 9, 6, 6]);
    expect(b.tiers[0].length).toBeCloseTo(150);
    expect(b.tiers[0].depth).toBeCloseTo(26);
    // Undefined and nonsense are the same as unreported, never a bowl of size zero.
    for (const bad of [undefined, 0, -5, Number.NaN]) expect(bowlFor(bad).tiers.map((t) => t.rows)).toEqual([9, 9, 6, 6]);
  });

  it('grows with the crowd, in both directions rather than only upward', () => {
    const big = bowlFor(107_601); // Michigan Stadium
    const mid = bowlFor(70_000);
    const small = bowlFor(25_000);
    expect(big.tiers[0].rows).toBeGreaterThan(mid.tiers[0].rows);
    expect(mid.tiers[0].rows).toBeGreaterThan(small.tiers[0].rows);
    expect(big.tiers[0].length).toBeGreaterThan(small.tiers[0].length);
    expect(big.seats).toBeGreaterThan(mid.seats);
    expect(mid.seats).toBeGreaterThan(small.seats);
  });

  it('takes the ends off a ground too small to have them, which is what those grounds look like', () => {
    expect(bowlFor(800).tiers).toHaveLength(2);
    expect(bowlFor(12_000).tiers).toHaveLength(2);
    expect(bowlFor(20_000).tiers).toHaveLength(4);
    expect(bowlFor(107_601).tiers).toHaveLength(4);
  });

  it('is bounded at both ends, because neither a bowl that vanishes nor one that swallows the field is useful', () => {
    const tiny = bowlFor(1);
    const vast = bowlFor(5_000_000);
    expect(tiny.tiers[0].rows).toBeGreaterThanOrEqual(3);
    expect(vast.tiers[0].rows).toBeLessThanOrEqual(13);
    expect(vast.tiers[0].length).toBeLessThanOrEqual(150 * 1.2);
  });

  it('stands its floodlights clear of the stands they light', () => {
    expect(bowlFor(107_601).towerX).toBeGreaterThan(bowlFor(null).towerX * 0.99);
    expect(bowlFor(800).towerX).toBeCloseTo(84);
  });
});

describe('the checked-in capacity table', () => {
  const table = { venues: VENUE_CAPACITIES };

  it('every row cites the entry it came from, so any one of them can be checked', () => {
    expect(table.venues.length).toBeGreaterThan(100);
    for (const v of table.venues) {
      expect(v.wikidata, v.name).toMatch(/^Q\d+$/);
      expect(v.espnId, v.name).toMatch(/^\d+$/);
      expect(v.capacity, v.name).toBeGreaterThan(0);
    }
  });

  it('holds one row per venue, so a lookup can never be ambiguous', () => {
    const ids = table.venues.map((v) => v.espnId);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it('holds one row per name too, which is what makes the name fallback safe', () => {
    // Captured scoreboards from before the provider published venue ids name their venues and
    // identify them with nothing, so the name is matched instead. That is only exact while no
    // two venues in the table share one.
    const names = table.venues.map((v) => v.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it('has the ones anybody would check by hand', () => {
    const by = new Map(table.venues.map((v) => [v.name, v]));
    expect(by.get('Michigan Stadium')?.capacity).toBe(107_601);
    expect(by.get('Lambeau Field')?.capacity).toBe(80_750);
    expect(by.get('Ohio Stadium')?.capacity).toBe(102_780);
  });
});
